---
title: "16s Amplicon Pipeline"
---

**Downloads**: <a href="https://mirror.las.iastate.edu/CRAN/" target="_blank">R</a> - 
<a href="https://www.python.org/" target="_blank">Python</a> - 
<a href="https://github.com/rdpstaff/RDPTools" target="_blank">RDP</a> - 
<a href="http://weizhongli-lab.org/cd-hit/" target="_blank">CD-Hit</a> - 
<a href="https://github.com/torognes/vsearch" target="_blank">vsearch</a> /
<a href="http://www.drive5.com/usearch/" target="_blank">usearch</a> - 
<a href="http://www.gnu.org/software/parallel/" target="_blank">gparallel</a>

# Why use this pipeline?

There are several complete pipelines that are well maintained and coumented; the two most popular being <a href="https://mothur.org/wiki/Main_Page" target="_blank">Mothur</a> and <a href="http://qiime.org/" target="_blank">Qiime</a>, with <a href="https://benjjneb.github.io/dada2/" target="_blank">DADA2</a> and <a href="https://github.com/biocore/deblur" target="_blank">deblur</a> gaining a lot of popularity recently. So there are many options. Mothur runs in its own environment; it has linear workflows and does not allow you to change the input/output file names. This can be confusing for users interested in intermediate steps of the workflow. Qiime is better about this; it is run using Python but hsa very fickle input requirements that can lead to a lot of lost time.

This pipeline was originally created by <a href="https://github.com/fandemonium" target="_blank">Fan Yang</a> in the  <a href="http://germslab.org/" target="_blank">GERMS-lab</a>. The purpose is that it allows much more control over every step, and is very transparent in how its workflow. She periodically updates <a href="https://github.com/germs-lab/amplicon_pipelines" target="_blank">her pipeline</a>, but I maintain my own version that I will update and annotate here.

# [Files][step0]

  + [**Sequence Files**](step_0.html#sequence_files)
  + [**Reference Database**](step_0.html#reference_database)
  + [**Mapping Files**](step_0.html#mapping_files)

# [Your Shell Environment][step1]

  + [**Paths to Your Data**](step_1.html#11_paths_to_your_data)
  + [**Paths to Programs**](step_1.html#12_paths_to_programs)
  + [**Sequence Read Parameters**](step_1.html#13_sequence_read_paramters)
  + [**Cores**](step_1.html#14_cores)

# [Read Processing][step2]

  + [**Pair-End Read Assembly**](step_2.html#21_pair-end_read_assembly)
  + [**Read Quality Filter**](step_2.html#22_read_quality_filter)
  + [**Demultiplexing**](step_2.html#23_demultiplexing)
  + [**Create Master Read File**](step_2.html#24_create_master_read_file) 

# [Chimera Removal][step3]

  + [**Dereplicating and Sorting Reads**](step_3.html#31_dereplicating_and_sorting_reads)
  + [**Chimera Detection**](step_3.html#32_chimera_detection)
  + [**Sort for Clustering**](step_3.html#33_sort_for_clustering)

# [OTU Calling][step4]

  + [**Clustering**](step_4.html#41_clustering)
  + [**Sample Mapping**](step_4.html#42_sample_mapping)
  + [**Taxa Classification**](step_4.html#43_taxa_classification)

# [HPCC][hpc]

# [Pipeline][pipe]

# Questions

If you have any questions, feel free to contact me by e-mail at <sdsmith@iastate.edu>

[step0]:step_0.html
[step1]:step_1.html
[step2]:step_2.html
[step3]:step_3.html
[step4]:step_4.html
[hpc]:hpcc.html
[pipie]:pipeline.html
